version: '3'
services:
  app:
    build:
      context: ./app
    expose:
      - "3000"
    environment:
      NODE_ENV: production      
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app